---
- name: Add nginx yum repo
  copy:
    src=nginx.repo
    dest=/etc/yum.repos.d
    owner=root
    group=root
    mode=0644
  tags:
    - essential

- name: Install nginx
  yum:
    name="nginx-{{nginx_version}}"
    state=present

- name: Remove default config files
  file:
    dest=/etc/nginx/conf.d
    state=absent

- name: Remove default site
  file:
    dest=/usr/share/nginx/html
    state=absent

- name: Copy nginx config file
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify:
    - Reload nginx

- name: Ensure the web root folder is created
  file:
    path="{{ nginx_root_path }}"
    owner=nobody
    group=nobody
    mode=0755
    state=directory

- name: Copy home page source file
  template:
    src=index.html.j2
    dest="{{ nginx_root_path}}/index.html"

- name: Copy home page images files
  copy:
    src=images
    dest="{{ nginx_root_path}}"

- name: Start nginx
  service:
    name=nginx
    state=started

